# Generated by Django 3.1 on 2002-01-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200821_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Hobbie',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
