# Generated by Django 3.1 on 2002-01-03 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0008_auto_20020103_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=20)),
                ('projects_link', models.URLField(blank=True, max_length=300, null=True)),
                ('resume_summary', models.TextField(max_length=400)),
                ('professional_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(choices=[(1, 'LEVEL 1'), (2, 'LEVEL 2'), (3, 'LEVEL 3'), (4, 'LEVEL 4'), (5, 'LEVEL 5')], default='1')),
                ('name', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.info')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.info')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.info')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('bsc', 'BSC'), ('hnd', 'HND'), ('nd', 'ND'), ('msc', 'MSC')], default='bsc', max_length=3)),
                ('studied', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.info')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.info')),
            ],
        ),
    ]
