# Generated by Django 3.1 on 2002-01-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_certificate_education_experience_hobbie_info_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.IntegerField(),
        ),
    ]
